### ISSUE TITLE
[Bug in Parsing] Year needs four digits

### ISSUE THREAD

**Issue by ghost** [aridevelopment-de/datetimeparser#182]
## Given input

1. > 20.2.**0791**
2. > 20.2.**791**

## Expected output

1. > 20-2-0791 0:00:00 (datetime)
2. > 20-2-0791 0:00:00 (datetime)

## Actual given output

1. > 20-2-0791 0:00:00 (datetime)
2. > Parser returned None

## Some extra notes

The parser can only handle years with 4 digits, but these digits can be 0 too.

**Comment by Ari24-cb24** [comment]
Datetime' strptime method is not capable of parsing such format. Dateutil is actually able to do that but their isoparse isn't as extensive as I would've hoped. I may have to write our own isoparse parser

**Comment by Ari24-cb24** [comment]
I decieded against it as this only affects three digit years. First of all, an implementation would worsen runtime performance and second of all this does not make sense for two or one digit year. Take for example `01.02.10`. You are not able to recognize whetever the 10 is the year or the 01. I strongly advocate the use of zero-padded years
