### ISSUE TITLE
[Bug in Parsing] Possible timezone parsing error with pytz library

### ISSUE THREAD

**Issue by qt-haskell** [aridevelopment-de/datetimeparser#203]
## Issue:
The pytz library has been known to cause issues when used in conjunction with `datetime.timezone`. 
As this is often used by other libraries, it is recommended to use the built-in `zoneinfo` library instead, which does not have these issues.

## Important Note:
If you are using `zoneinfo` on a Windows machine, be sure to also install `tzdata` to ensure proper functioning.

## Further information:
- https://docs.python.org/3/library/zoneinfo.html
- https://pypi.org/project/tzdata/

**Comment by Ari24-cb24** [comment]
Thanks for creating an issue! @Inf-inity You should take a look at this

**Comment by ghost** [comment]
`pytz` was replaced in this [commit](https://github.com/aridevelopment-de/datetimeparser/commit/5c01aa83b43a973b52acb2c45ea34442b418cf2a) with `zoneinfo.ZoneInfo()`

---
Note:  
- It wasn't tested on windows yet, until it's tested the issue will remain open for now
