### ISSUE TITLE
Add more Eventes

### ISSUE THREAD

**Issue by leon-3** [aridevelopment-de/datetimeparser#26]
Here are some ideas for events to add

- [x] Beginning of Advent of Code
- [x] End of Advent of Code
- [x] Beginning/End of Summer/Spring/Fall/Winter
- [x] April Fool's Day
- [x] Thanksgiving
- [ ] (Independence Day)
- [ ] Black Friday
- [ ] Cyber Monday

**Comment by Ari24-cb24** [comment]
I don't think Black Friday and Cyber Monday is a good idea

**Comment by Ari24-cb24** [comment]
still things missing so remember to reopen on merged prs

**Comment by Ari24-cb24** [comment]
I still dont know about independence day tho. Open to discuss but open a new issue please
